# -*- coding: utf-8 -*-
"""pipeline model lengkap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Md9Hst6t55KWMc2Xr7IHL69WBibFInmj
"""

# from google.colab import drive
# drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, mean_squared_error
from scipy.stats import zscore

file_path = "df_trimmed.xlsx"

# baca sheet utama
df_bdv = pd.read_excel(file_path, sheet_name=0)
df_suhu = pd.read_excel("clean suhu x ppm.xlsx")

X_suhu = df_suhu['suhu'].values.reshape(-1,1)
y_suhu = df_suhu['moisture'].values

log_y_suhu = np.log(y_suhu)

exp_model_suhu = LinearRegression()

exp_model_suhu.fit(X_suhu, log_y_suhu)

log_pred_suhu = exp_model_suhu.predict(X_suhu)

y_pred_suhu = np.exp(log_pred_suhu)

a = np.exp(exp_model_suhu.intercept_)
b = exp_model_suhu.coef_[0]

print("Exponential Model Equation:")
print(f"ppm = {a:.4f} * exp({b:.4f} * T)")

def normalize_ppm_new(ppm, T, T_ref=30):
    if T <= T_ref:
        return ppm
    else:
      b = exp_model_suhu.coef_[0]
      ppm_ref = ppm * np.exp(b*(T_ref - T))
      return ppm_ref

#RF Model
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.ensemble import RandomForestRegressor


X_bdv = df_bdv[['moisture']]
y_bdv = df_bdv['bdv']

# model
rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

rf_model.fit(X_bdv, y_bdv)

ppm_sensor = 50
temp_sensor = 60

ppm_30 = normalize_ppm_new(ppm_sensor, temp_sensor)

print("PPM sensor:", ppm_sensor, "ppm")
print("Temperatur sensor",temp_sensor,"celcius")
print("PPM normalized (pada 30 celcius):", round(ppm_30,2), "ppm")

bdv = rf_model.predict([[ppm_30]])
print("BDV:",round(bdv[0],2), "kV")